services:
  app:
    image: empiricusadm:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/empiricusADM
      - SPRING_DATASOURCE_USERNAME=xxwelldone
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'postgres:16.0-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=xxwelldone
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=empiricusADM
    ports:
      - "5432:5432"